# Generated by Django 4.2.2 on 2023-06-07 17:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('api', '0002_alter_chatsession_title'), ('api', '0003_answer_answer_id_question_question_id_and_more'), ('api', '0004_alter_answer_context_alter_answer_model_and_more'), ('api', '0005_rename_downvotes_answer_rating_remove_answer_upvotes'), ('api', '0006_remove_answer_edit_history_remove_question_tags_and_more')]

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Chat Session', max_length=100),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.chunk'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.llm'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.prompttemplate'),
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='downvotes',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='edit_history',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
