# Generated by Django 4.2.2 on 2023-06-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chatsession_title_squashed_0006_remove_answer_edit_history_remove_question_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sources_last_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chunk'),
        ),
    ]
