# Generated by Django 4.2.2 on 2023-06-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_collection_sources_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
