# Generated by Django 4.2.2 on 2023-06-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chatsession_color'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='llm',
            name='current_model',
        ),
        migrations.RemoveConstraint(
            model_name='prompttemplate',
            name='current_template',
        ),
        migrations.RenameField(
            model_name='llm',
            old_name='active_model',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='prompttemplate',
            old_name='active_prompt',
            new_name='active',
        ),
        migrations.AddConstraint(
            model_name='llm',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='current_model'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('template',), name='current_template'),
        ),
    ]
