# Generated by Django 4.2.2 on 2023-06-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_llm_current_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.llm'),
        ),
    ]
