# Generated by Django 4.2.2 on 2023-06-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_answer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='token_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='token_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='token_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
