# Generated by Django 4.2.2 on 2023-06-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_answer_token_size_chunk_token_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="updating",
            field=models.BooleanField(default=False),
        ),
    ]
