# Generated by Django 4.2.2 on 2023-06-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_faqentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='times_referenced',
            field=models.IntegerField(default=0),
        ),
    ]
