apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "client.fullname" . }}-config
  labels:
    {{- include "client.labels" . | nindent 4 }}
data:
    PUBLIC_APP_URL: {{ .Values.publicAppURL }}
    PUBLIC_API_URL: {{ .Values.publicAPIURL }}
    PUBLIC_EVENT_STREAM_URL: {{ .Values.publicEventStreamURL }}