apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-app
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.appService.type }}
  ports:
    - port: {{ .Values.appService.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
