apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-app-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
data:
  APP_URL: {{ .Values.ingress.host | quote }}
  INTERNAL_NAME: "{{ include "backend.fullname" . }}-app"
  FRONTEND_URL: {{ .Values.frontendURL | quote }}
  BACKEND_URL: {{ .Values.backendURL | quote }}
  PUSHPIN_CONTROL_URI: "http://{{ include "backend.fullname" . }}-pushpin:5561"
  AI_SERVICE_URL: {{ .Values.aiServiceURL | quote }}
  QDRANT_URL: {{ .Values.qdrantURL | quote }}
  CACHE_URL: {{ .Values.cacheURL | quote }}
  CELERY_BROKER_URL: {{ .Values.celeryBrokerURL | quote }}
  EMBEDDING_SIZE: {{ .Values.embeddingSize | quote }}
  DECAY_SCALAR: {{ .Values.decayScalar | quote }}
