{{- if .Values.database.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-app-db
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
type: Opaque
data:
  DATABASE_URL: {{ .Values.database.url | b64enc }}
{{- else }}
{{ required "A valid .Values.database.secretName entry required if .Values.database.url is not set!" .Values.database.secretName }}
{{- end }}
