apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-pushpin-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "backend.fullname" . }}-pushpin
binaryData:
{{- range $path, $bytes := .Files.Glob "pushpin-config/*" }}
{{ base $path | indent 2 }}: {{ tpl ($.Files.Get $path) $ | b64enc }}
{{ end }}
