CHANNEL = "test"
MODEL_NAME = "model_name"
MODEL_ID = "model_id"
SESSION_ID = "session_id"
MESSAGE_ID = "message_id"
PROMPT = "prompt"
GENERATED_TEXT = "generated_text"
TEXT = "text"
GENERATED_EMBEDDING = [0.0, 0.0, 0.0]
GENERATED_TOKENS = [0, 0, 0]
