{{- if or .Values.weightsPVC .Values.weightsS3.secretName }}
{{- else if and .Values.weightsS3.accessKey .Values.weightsS3.secretKey .Values.weightsS3.bucketName .Values.weightsS3.serverEndpoint }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-service.fullname" . }}-models
  labels:
    {{- include "ai-service.labels" . | nindent 4 }}
type: Opaque
data:
  ACCESS_KEY: {{ .Values.weightsS3.accessKey | b64enc }}
  SECRET_KEY: {{ .Values.weightsS3.secretKey | b64enc }}
  BUCKET_NAME: {{ .Values.weightsS3.bucketName | b64enc }}
  SERVER_ENDPOINT: {{ .Values.weightsS3.serverEndpoint | b64enc }}
{{- else }}
{{ required "Either of weightsPVC, weightsS3.secretName or (weightsS3.accessKey, weightsS3.secretKey, weightsS3.serverEndpoint) must be set." .Values.weightsPVC }}
{{- end }}
