apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proqa-gg-ax
  namespace: default
spec:
  secretName: proqa-tls
  commonName: proqa.gg.ax
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - '*.proqa.gg.ax'
    - 'proqa.gg.ax'
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
